In [2]:
import math
import os
import random
import re
import sys

#
# Complete the 'formingMagicSquare' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY s as parameter.
#

def formingMagicSquare(s):
    return NotImplemented
    # Write your code here


In [69]:
import numpy as np

random.seed(1)
S = np.array([random.randint(1, 9) for i in range(9)]).reshape(3,3)
print(S)

[[3 2 5]
 [2 8 8]
 [8 7 4]]


In [96]:
n = 3

A = np.zeros([8, 10])
for i in range(n*2 + 2):
    if i<n:
        for j in range(n):
            A[i][j+i*n] = 1
    elif n<=i<2*n:
        for j in range(n):
            A[i][j*n+i-n] = 1
    elif i==6:
        A[i][0]=1
        A[i][4]=1
        A[i][8]=1
    elif i==7:
        A[i][2]=1
        A[i][4]=1
        A[i][6]=1

b = np.zeros([A.shape[0], 1])

for i in range(A.shape[0]):
    b[i] = np.dot(A[i][:-1], S.reshape(n**2))

print(A)
print(b)

P = np.diag([2 for i in range(n**2)]+[2])
q = -2*np.array(S.reshape(n**2).tolist() + [0]).reshape(n**2+1,1)

print(P)
print(q)

Aext = np.block([[P, A.T], [A, np.zeros([A.shape[0], A.shape[0]])]])
inv = np.linalg.inv(Aext)
solve = np.dot(inv, np.block([[-q], [b]]))

[[1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 0.]]
[[10.]
 [18.]
 [19.]
 [13.]
 [17.]
 [17.]
 [15.]
 [21.]]
[[2 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 2]]
[[ -6]
 [ -4]
 [-10]
 [ -4]
 [-16]
 [-16]
 [-16]
 [-14]
 [ -8]
 [  0]]


In [134]:
d = {str(i): i for i in range(4)}

for k,v in d.items():
    print(k)

0
1
2
3


In [127]:
s = "-12.34"
s.replace(".", " ")
print(s.replace(".", "").replace("-", "").replace("+", ""))
s.replace(".", "").replace("-", "").replace("+", "").isdigit()


1234


True

In [91]:
np.block([[-q], [b]]).shape

(9, 1)

In [3]:
import numpy as np

s = []

for _ in range(3):
    s.append(list(map(int, input().rstrip().split())))

result = formingMagicSquare(s)

fptr.write(str(result) + '\n')

fptr.close()

KeyError: 'OUTPUT_PATH'